# Generated by Django 3.0.8 on 2020-09-29 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='thumbnail',
            field=models.ImageField(default='https://www.tibs.org.tw/images/default.jpg', upload_to='thumbnails/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='https://www.tibs.org.tw/images/default.jpg', upload_to='carpics/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Car')),
            ],
        ),
    ]
