# Generated by Django 3.0.8 on 2020-09-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200929_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
